version: '3.4'

services:
    core:
        build:
            context: ./src/core
            dockerfile: ./Dockerfile
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}
        ports:
            - 3000:3000
            - 5050:5050